package:
  name: mysql-connector-python
  version: !!str 2.0.1

source:
  fn: mysql-connector-python-2.0.1.zip
  url: http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.1.zip
  md5: abe12e0d30c05f16723b4f0d65e7f2eb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mysql-connector-python = mysql-connector-python:main
    #
    # Would create an entry point called mysql-connector-python that calls mysql-connector-python.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
      - mysql.connector
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://dev.mysql.com/doc/connector-python/en/index.html
  license: GNU General Public License (GPL)
  summary: 'MySQL driver written in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
